### PR TITLE
trigger a shortcutSubmit event when pressing ctrl + enter in taptip

### PR DESCRIPTION
**Pull request by Combo819**

### CODE REVIEW

**Comment by izgzhen** [comment]
Thank you!

**Comment by izgzhen** [comment]
@Combo819 Somehow when I formatted the code with cli tool (see `Makefile`), I got a different format. Let's try to keep in sync with the cli version.

**Comment by Combo819** [comment]
@izgzhen I used the vscode prettier extension.  Should we add a format npm script?

**Comment by izgzhen** [comment]
@Combo819 I just moved the commands from `Makefile` to `package.json`. You can use `yarn run format` to format the files, and use `yarn run check` to check the format. Please run `yarn install` as well since I just explicitly added the prettier local dependency.

**Comment by Combo819** [comment]
@izgzhen Ok. Thanks

**Pull request merged**
